### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Rohit-Satyam** [mdozmorov/scRNA-seq_notes#2]
Dear Dr. Mikhail

Thanks for organizing all the resources beautifully. They help me a lot and I wish to contribute to it. My suggestions are:
1. simpleSingleCell seems to migrate to "Orchestrating Single-Cell Analysis with Bioconductor". I don't know if this is still helpful and maybe you can remove this resource. It can possibly be replaced by this workflow: https://kkorthauer.org/fungeno2019/singlecell/vignettes/1.2-preprocess-droplet.html OR http://bioinformatics.age.mpg.de/presentations-tutorials/presentations/modules/single-cell//bioconductor_tutorial.html

**Few more suggested addition:**
1. Dave Tangs Blog: https://davetang.org/muse/2018/08/09/getting-started-with-cell-ranger/
2. ASAP: https://asap.epfl.ch/home/tutorial?t=full_pipeline
3. pbmc_roche: https://almutlue.github.io/batch_dataset/pbmc_roche.html#
4. Rockfeller University latest scRNAseq tutorial: https://rockefelleruniversity.github.io/scRNA-seq/

**Comment by mdozmorov** [comment]
Thank you, Rohit, for the suggestions. I added all, fixed some formatting. If you see any other missing resources or imperfections, please, open another issue, or make a PR.
